### ISSUE TITLE
关于8月18日开始的双周特供贴画"Seahorse" emblem of the 3./BoFlGr 196, Luftwaffe译名问题

### ISSUE THREAD

**Issue by GrafVonZeppelin** [YukinonV/WTCNtranslations#1]
游戏中以196舰载机航空航空团为错误译名，应改为196船基航空大队
其一BoFlGr 全称为Bordfliegergruppe 
这是属于大队（gruppe）编制而不是航空团（Geschwader）编制
来源：https://en.m.wikipedia.org/wiki/Bordfliegergruppe_196
其二BoFlGr 196（暂称196航空大队）是海军舰艇搭载的水上侦察飞机所属部队，二战时装备较为著名的Ar196。而Trägergruppe 186 即186舰载机航空大队为齐柏林伯爵型航空母舰所搭载的航空大队，主要装备飞机为Ju87与Bf109。我个人认为196航空大队与186航空大队职责任务与成立原因都不相同，不应将196称为舰载机航空大队，且目前舰载机多指航空母舰所搭载的飞机而非军舰搭载的水上飞机。综上所述应译为196船基航空大队。

**Comment by YukinonV** [comment]
感谢反馈，Bordfliegergruppe 系列会进行统一的修改！
