### ISSUE TITLE
一些反馈和建议

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#10]
![image](https://user-images.githubusercontent.com/94670721/230248781-b5a2d177-6509-4444-86e1-6b39c0440663.png)
“自动控制起落架和襟翼”→“自动控制起落架”

![image](https://user-images.githubusercontent.com/94670721/230248992-c7337168-6c41-48a6-b9f7-24419e5a21cc.png)
“按键设置”→“控制”、“退出游戏”→“退出”

https://warthunder.com/zh/game/changelog/current/306
“音效重置”→“音效重制”

https://warthunder.com/zh/game/technics/
“军用车辆”→“军用载具”

**Comment by YukinonV** [comment]
感谢反馈，经过对问题的排查现回复如下：

- “自动控制起落架和襟翼”是开发方面变更词条没有更新导致的，现已更改，等待实装
- “退出游戏”可改可不改，因为这个选项的含义便是关闭游戏客户端并退出与中途结束战局的“离开游戏”并无冲突或重复之处，是否更改需要进行讨论
- 官方网站推文翻译中的措辞问题不是由我们负责的，已进行转达（据我所知负责推文翻译的工作人员仅负责翻译推文内容，商店与首页按钮与其他外观方面的词条应该是由俄方负责的）

**Comment by YukinonV** [comment]
考虑到游戏内UI长度适配的因素，中文词条目前的规范是载具名称词条里仅用半角符号+空格，尽可能让科技树和击杀反馈内的信息不至于溢出（实在太长的也没有办法）。其他文本信息则用全角符号。当然资料卡载具分类使用全角符号的确看上去不是那么统一，具体更改方案还需要统计一下受影响载具数量，如果的确是普遍问题则会进行更改。

Strike aircraft这个分类完全是毛子生造的，游戏中已经有专门的攻击机分类了，也就是Attacker。我个人猜想毛子弄这个分类是想囊括所有对空对地能力兼备的战机，区别于纯对地的攻击机（从IL-2也被归入此类来看，他们可能并不知道自己在做什么）。很显然，现代战机中常用的Fighter-Bomber分类不适配Me 410这种二战老玩意，于是就有了Strike aircraft这个完全缝合的分类。这个分类是完全出于游戏性考虑的（影响出生点和任务之类），我个人也一直想替换掉目前的翻译，但是目前并没有找到更好的说法可以形容这种分类。如果您有好的想法欢迎提出来。

关于Control，我同意您的意见，这一选项的确涵盖了轴编辑等功能，个人认为可以改为“操作方式”。不过这个词条历时较久，如果贸然更改可能会引起玩家的适应性问题，容易引起争议。需要进一步讨论。

**Comment by JackerGamer** [comment]
> Strike aircraft这个分类完全是毛子生造的，游戏中已经有专门的攻击机分类了，也就是Attacker。我个人猜想毛子弄这个分类是想囊括所有对空对地能力兼备的战机，区别于纯对地的攻击机（从Hs 129也被归入此类来看，他们自己可能也对这一分类的具体含义缺乏概念）。很显然，现代战机中常用的Fighter-Bomber分类不适配Me 410这种二战老玩意，于是就有了Strike aircraft这个完全缝合的分类。这个分类是完全出于游戏性考虑的（影响出生点和任务之类），我个人也一直想替换掉目前的翻译，但是目前并没有找到更好的说法可以形容这种分类。如果您有好的想法欢迎提出来。

我在科技树只看到了”Strike Aircraft“一种名称，请问”Attacker“在哪里有使用？（英文版本）

**Comment by YukinonV** [comment]
Attacker作为载具分类的词条依旧留存在游戏文本当中，Strike aircraft并没有完全替代Attacker分类（至少在街机与世界大战等特定模式下仍旧有相关词条保留）。需要证实Attacker作为载具类别确实已经完全被Strike aircraft代替才能进行更改。

**Comment by YukinonV** [comment]
经过讨论，目前暂时决定Control更译为“操作设置”，Settings扩译为“游戏选项”（以保持菜单界面文本整体一致性），Strike aircraft更改为“攻击机”（视后续反馈再行变动）。其他UI元素需要进一步研究才能更改。

**Comment by JackerGamer** [comment]
辛苦了，您的意思是“Options”译为“游戏选项”、“Controls”译为“操作设置”？

**Comment by YukinonV** [comment]
是这样的，感谢反馈

**Comment by JackerGamer** [comment]
> 经过讨论，目前暂时决定Options更译为“游戏选项”，Settings扩译为“操作设置”（以保持菜单界面文本整体一致性），Strike aircraft更改为“攻击机”（视后续反馈再行变动）。其他UI元素需要进一步研究才能更改。 鉴于资料卡中全角/半角符号不统一的问题，在对地打击机（战斗/攻击机）译名更改后将不会那么严重，会在翻译变动实装后再行观察。

你好，请问为什么新版本“Controls”的中文仍为“按键设置”？
