### ISSUE TITLE
建议统一部分飞机命名

### ISSUE THREAD

**Issue by GHOSTLYH** [YukinonV/WTCNtranslations#11]
1.个人建议外贸机应当统一使用外贸编号，若有对应国内名字再辅以括号，即英文字母+数字+（国内名），以区分其自用/外贸的不同。如歼五出口型个人建议应该改为F-5，强五III个人建议应当改为A-5C（强5-III），以后有可能出的老强5D/强5M建议仅称为A-5M ，此规则也适用于F-6，F-7以及其他的。FC/FBC/FTC/TC此类新时代外贸机则可以直接用唯一名字，如果对应国家给予其服役代号建议仅使用其服役代号，如JF-17.
2.国内由于80年代使用了新的字母编号，建议获得新代号飞机直接使用新代号，以强五系列为例，强5I个人建议应当改为强5A，强5IA为强5B，强5II为强5C（也是前一点提出外贸机外贸编号在前的原因之一），未获得新编号的飞机则使用旧编号，其他如歼六和部分歼7歼8亦如是。
3.小小吐槽，为啥歼6甲中间要加个空格呢，我翻找的资料中天干地支（用途改造）和罗马数字（性能升级）都是直接加在数字后面的，如歼-6甲，歼-6III，建议把这个空格去了。
辛苦

**Comment by YukinonV** [comment]
感谢反馈
目前游戏内翻译只是遵循既有规范，对于外贸战机命名进行这种程度的变动需要进行谨慎讨论，并且听取更多玩家的意见才能进行。单以出口型歼5为例，目前该机的权重是9.3，实战中（尽管概率相对较低）仍有可能遭遇美系F-5A/C（10.3），而空历在远距离渲染会显示简化名称，这样一来远距离会全部显示成“F-5”，会为游戏中的威胁评估乃至接敌战术带来不必要的麻烦。
子型号命名规范这一点之前似有论证，现行规范的具体运用理由以及为何没有采用拉丁字母这一点我尚不清楚（似乎是以战机的初始定型名称为准绳），会将您的意见提交反馈。
歼-6 甲的数字与汉字编号之间的空格是游戏内文本排版统一规范：半角字符（数字）与全角字符（汉字）之间留出空格起到分划作用，相较不留空格在排版上更为整齐便于阅读。

**Comment by Zyszhao** [comment]
其实英文里面条目就是Shenyang F-5和A-5C，而前者在最远距离下的显示是Shenyang……这个有必要交issue，太意义不明了
好死不死美国的A-5只出到了A-5B，C是侦察型RA-5C，不过现在A-5C最远距离下的显示是A-5
其实这事情我觉得应该给蜗牛反馈，把A5C和金歼5的最远距离改成Q-5和MiG-17
另外，JF-17这些没出的其实还得取决于蜗牛给的词条如何
