### ISSUE TITLE
几个装备词条命名的疑问

### ISSUE THREAD

**Issue by Zyszhao** [YukinonV/WTCNtranslations#12]
1.关于以色列的强壮坦克炮，我之前查到的Sharir的翻译更接近于“肌肉”，而强壮的读音相差甚远，请问这是翻译问题还是希伯来语比较乱遭？
2.一些枪炮中XX“型”XX，这个“型”是什么标准？比如我在法国的一些装备原文上看不出有“型”的来源
3.Flares reinforced在实际使用中我看到不少以为“更多热焰弹”是增加携带的热焰弹数量，可否更改？
4.Hotchkiss在词条中似乎同时被翻译成霍奇基斯和奥奇基斯
另，weapons/us_aim9g_sidewinder中的响尾蛇仍然有引号。

**Comment by YukinonV** [comment]
感谢反馈
沙里尔坦克炮的译名更改由来我并不清楚，需要再查证之后才能作出决定。
法/意枪炮目前应该是把 Mle + 年份或者 Model + 年份统一翻译成 XX 型，SA前缀的坦克炮保持原名称不变。目前只是按照既有规范进行翻译，并不清楚具体缘由。
Flares reinforced等等设置的是一次抛射发射的热诱数量，鉴于官方有意对目前的干扰措施抛射系统进一步细化（进一步细分抛射类型和允许更自由搭配），一切变动还是等到官方机制更新为妥。
霍奇基斯M1930型重机枪与AIM-9G词条已更正，等待实装。

**Comment by JackerGamer** [comment]
> 1.关于以色列的强壮坦克炮，我之前查到的Sharir的翻译更接近于“肌肉”，而强壮的读音相差甚远，请问这是翻译问题还是希伯来语比较乱遭？

https://www.collinsdictionary.com/dictionary/hindi-english/%E0%A4%B6%E0%A4%B0%E0%A5%80%E0%A4%B0

**Comment by Zyszhao** [comment]
> > 1.关于以色列的强壮坦克炮，我之前查到的Sharir的翻译更接近于“肌肉”，而强壮的读音相差甚远，请问这是翻译问题还是希伯来语比较乱遭？
> 
> https://www.collinsdictionary.com/dictionary/hindi-english/%E0%A4%B6%E0%A4%B0%E0%A5%80%E0%A4%B0

这是印地语吧……

**Comment by JackerGamer** [comment]
抱歉，当我没发🤧
