### ISSUE TITLE
“Send to holiday”的陈年翻译

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#13]
虽然“临时闲置”易于理解，但是它没有体现原文的幽默。参考繁体的“给乘员组放假”，私以为简体用“送去度假”更好（包括人和载具）。

**Comment by YukinonV** [comment]
感谢您的建议，我们会进行讨论决定是否采纳。

**Comment by JackerGamer** [comment]
顺便问问，游戏内的中文字体是什么？

**Comment by YukinonV** [comment]
可能是微软雅黑，具体授权情况不清楚

**Comment by Zyszhao** [comment]
以功能性的角度来看，这种翻译有点令人费解。
我认为改为“闲置乘员组”比较恰当。

**Comment by YukinonV** [comment]
您好，经过讨论决定，既有翻译没有原则错误或理解歧义的情况下一般不进行更改。
感谢您的反馈。
