### ISSUE TITLE
炸药装药成分

### ISSUE THREAD

**Issue by Zyszhao** [YukinonV/WTCNtranslations#14]
炸药装药成分是中文汉化所特有内容，这些与英文原文不符
请问有将其删去的计划吗？这些内容对性能影响大吗？

**Comment by YukinonV** [comment]
感谢反馈
我们注意到了相应问题，并计划移除此类不必要的文本内容避免引起玩家误解。

**Comment by YukinonV** [comment]
已进行删减 & 对部分词条进行修正，等待实装
