### ISSUE TITLE
Efficient progress from

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#15]
“特殊研发加成”意为“所增加部分的比例”，与原文不符；所以我建议翻译为“（特殊）研发效率”。
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/8a5b4261-6088-4027-8b2e-f2d0838d7047)

**Comment by YukinonV** [comment]
感谢反馈
我认同您的意见，从消除歧义的角度而言的确更改好一点，不过具体用词可能还需要再斟酌一下。

**Comment by JackerGamer** [comment]
> 感谢反馈 我认同您的意见，从消除歧义的角度而言的确更改好一点，不过具体用词可能还需要再斟酌一下。

有段时间了，请问具体用词还没决定吗……

**Comment by YukinonV** [comment]
抱歉回复延误
原文词条为Efficient progress from {载具名称变量}，实际给予10%的加成，的确与游戏中其他加成的作用形式不同。
目前拟定为 使用 {载具名称变量} 的研发效率：，考虑到资料卡宽度问题，去除了特殊二字。
