### ISSUE TITLE
关于“At min./max. stake”

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#16]
说实话，我第一次看合同说明时困惑了很久（＞︿＜）。现中文为“最低/最高押金”，但原文不是指押金金额，而是指在什么押金下的奖励金额；所以我建议改为“在最低/最高押金下”。
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/ec4fb222-3987-4305-98d3-b2c6502c955c)

**Comment by YukinonV** [comment]
拟改为“最低（押金）报酬”与“最高（押金）报酬”。不过我不是很确定银狮合同的具体机制，需要先行实验一下。

**Comment by YukinonV** [comment]
考虑到文字宽度，已更改为最低报酬与最高报酬，等待实装。
