### ISSUE TITLE
“连续投弹”或许需要修改

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#17]
“Drop bomb series”功能是“同时投放多枚炸弹”，而非“一枚接一枚地投放炸弹”。在副武器·顺次发射数量中也有连续发射模式“Continuous mode”，功能与“Drop bomb series”并不同。所以个人建议修改此翻译，以免引起玩家的困惑。

**Comment by Zyszhao** [comment]
emmm 这个功能如果调成0还是怎么样来着确实是一枚接一枚的投弹 还是不改比较好吧

**Comment by JackerGamer** [comment]
> emmm 这个功能如果调成0还是怎么样来着确实是一枚接一枚的投弹 还是不改比较好吧

你说得对，选择“禁用”就是一枚接一枚地投放，但是如此也符合“禁用同时投放”的意思啊

**Comment by YukinonV** [comment]
具体来说确实存在部分设置情况下效果为连续投弹的顾虑，目前没有比较好的概述两种情况的说法。
对于此类不存在明显歧义或重复的词条是否需要更改我个人持谨慎态度。感谢您的讨论。

**Comment by JackerGamer** [comment]
Drop bomb - 投放炸弹
Drop bomb series - 投放多枚炸弹
这样修改是否可行？

**Comment by JackerGamer** [comment]
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/9af9b7ab-895a-4394-96b8-314bb58d303f)
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/660cca37-c52d-4f99-b80f-b1a0946a05f2)

这次更新后，在武器选择模式开启时无法使用连续投弹按键——这是功能冲突而非按键冲突。

参见：
https://community.gaijin.net/issues/p/warthunder/i/RD6HjmVfT6M0
https://tieba.baidu.com/p/8610060533

**Comment by YukinonV** [comment]
功能冲突时的提示符已经修正，感谢反馈
关于连续投弹功能，考虑到语义方面歧义不大（接连投下单枚炸弹与一次性投放多枚炸弹），暂时不进行更改。

**Comment by YukinonV** [comment]
适配新详情词条的加入，原有的“连续投弹”已更正为“分批投弹”、即按一下投弹键投放指定数量的炸弹，直至所有炸弹投放完毕为止。感谢您的宝贵建议。

**Comment by YukinonV** [comment]
更改词条：
Bomb series - 分批投弹
{num} {num=bomb/bombs} will be dropped by series - 每个投放批次将会连续投放 {num} {num=颗炸弹/颗炸弹}
All bombs will be dropped by series - 所有炸弹将分批完成投放

**Comment by JackerGamer** [comment]
挺好的，或许可以简洁一点：

> 每个批次将投放 {num} {num=颗炸弹/颗炸弹}
> 所有炸弹将分批投放

**Comment by YukinonV** [comment]
感谢反馈
第一个“连续”个人认为可去可不去，其余多余用词已经进行简化。
