### ISSUE TITLE
TWS≠扫描追踪

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#18]
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/81ae2bac-7d9e-4b8b-90ae-0e2fa3519926)

Track While Scan的正确翻译应为“边扫描边跟踪”。

`边扫描边跟踪（TWS）是一种雷达工作模式，在这种模式下，雷达将其部分功率用于跟踪目标，而将其部分功率用于扫描。这与直接跟踪模式不同，在直接跟踪模式下，雷达将其全部功率用于跟踪获取的目标。在TWS模式下，雷达有可能获取更多目标，并提供空域全貌，有助于保持更好的态势感知。——摘自英文维基百科`

**Comment by Zyszhao** [comment]
我怀疑这个和右侧雷达是一个词条，之前有人说过“扫描并跟踪”糊到一起了

**Comment by JackerGamer** [comment]
之前在这个视频看到的：[https://www.bilibili.com/video/BV1K3411A7PX/](url)

**Comment by YukinonV** [comment]
该词条是之前修改HUD元素时的临时措施（缩写），更改到了内构描述上，目前已更改为“扫描并追踪”。
