### ISSUE TITLE
投诉玩家和投诉类别

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#19]
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/4a6f52f7-6c95-402c-a0c7-12603cbb88c7)
首先，当前“Complain”的翻译为“投诉”，“Complaint”翻译为“举报”，建议统一用词为“投诉”。
其次，投诉类别的“使用自动脚本和外挂”有误。我在官方论坛和Reddit查了下，“Passive behaviour”的意思类似于“消极作战”。
因此，建议投诉类别依次改为：脏话、辱骂、伤害队友、消极作战、垃圾消息、其他。

**Comment by YukinonV** [comment]
你好，感谢反馈
Complain已由“举报”统一为“（发送）投诉”。Passive behaviour一并更正，等待实装。
