### ISSUE TITLE
关于统一后缀的问题

### ISSUE THREAD

**Issue by qzwww1234** [YukinonV/WTCNtranslations#2]
请问是否可以按照常用译名和用法对游戏中目前的一些同词不同译的翻译内容进行归一化，如38（t）坦克歼击车、猎豹坦克歼击车和四号歼击坦克，后缀都为jagdpanzer，后者翻译却不同。另外安装长管75mm炮的四号坦克/70(V)和70（A）也没有后缀便于辨别，是否可以将其统一，按常用译名作—>四号坦克歼击车和四号坦克歼击车70（A）/70(V)，包括火炮式歼击坦克和导弹式歼击坦克也有类似问题。

**Comment by YukinonV** [comment]
现在游戏中的文本还处于评估阶段，按照社区的反馈和 Gaijin 的要求，游戏中的内容短期内都是以英文为基准的。并且同一种翻译方式只会是对应某一个载具，或者某一个车族，而不会运用到全部的同类型的载具上。
