### ISSUE TITLE
头衔翻译重复

### ISSUE THREAD

**Issue by MeltTrigger** [YukinonV/WTCNtranslations#20]
Aerial Supremacy、苍空卫士：2023 年“苍空卫士”锦标赛决赛优胜者专属头衔 与 2020夏季特卖的 Air Superiority、苍空卫士 头衔翻译重复

**Comment by YukinonV** [comment]
感谢反馈
Aerial Supremacy头衔计划更改为“长空霸主”，具体改正方案仍在讨论当中

**Comment by JackerGamer** [comment]
由于这两个词组是军事术语，个人建议直译为“空中霸权”和“空中优势”。

**Comment by YukinonV** [comment]
> 由于这两个词组是军事术语，个人建议直译为“空中霸权”和“空中优势”。

对于奖励头衔而言是有一定发挥空间的，如果有好的想法欢迎留下建议

**Comment by MeltTrigger** [comment]
> 由于这两个词组是军事术语，个人建议直译为“空中霸权”和“空中优势”。

这个锦标赛名为“Air Superiority Tournament”，译为“苍空卫士”锦标赛是没问题的，只是冠军的头衔需要和之前促销活动做出区分即可
