### ISSUE TITLE
斜线”/“在载具名称中的用法

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#21]
在英语中，斜线经常用于连接词句，也被用来表示“和”、“或”。在战雷的英文版本中，斜线主要是用来表示载具折叠的，只有少数载具名称含有斜线。然而，在中文版，一些原本没有斜线的名称被加上了斜线，如“酋长/神射手”、“豹2/PSO”。这可能会造成混淆，希望您能调整斜线的使用方式。

小问题：“黄鼠狼1A1-”多打了一个连字号，应改为“黄鼠狼1A1”。 “狂风 IDS ASSTA 1”多打了一个空格，应改为“狂风 IDS ASSTA1”。

**Comment by Zyszhao** [comment]
据我所知 汉化的斜线用来表示载具的武器/武器系统配置 所以其实也是有一定道理的
比如“酋长/神射手”是酋长接头神射手的意思

**Comment by YukinonV** [comment]
感谢反馈。

在先前的既定翻译规范中，斜杠用于表示武器系统或装甲套件类型，您提到的可能存在混淆等问题我们在编制载具编组名称时已经考虑到了，但目前PSO并没有被折叠，而神射手与布雷努斯等的编组名称已经进行了消歧义。实际上问题更多出在载具编组图标没有及时更新、导致部分编组还在使用单载具图标引起混淆问题。

黄鼠狼1A1-原文如此，实际是为了将简配版升级型黄鼠狼与配备了热成像的1A1(+)相区别，因此不是错误。

狂风 IDS 已经进行了更正，感谢提醒。
