### ISSUE TITLE
"开关飞行辅助控制"应改为“切换飞控模式”

### ISSUE THREAD

**Issue by Potat0Servers** [YukinonV/WTCNtranslations#22]
在飞机和直升机的键位设置里 开关飞行辅助控制 这一项翻译很容易引起歧义 实际功能是切换飞控模式
![image](https://github.com/YukinonV/WTCNtranslations/assets/66018299/a44e59a6-511f-4b20-9034-59ffb4626d5c)

在英文模式下意思是正确的
![image](https://github.com/YukinonV/WTCNtranslations/assets/66018299/b6dda7ec-355b-4436-b3fc-f14fe707a0af)

希望能够修正

**Comment by YukinonV** [comment]
感谢反馈

已经对文本进行更正，等待实装。
