### ISSUE TITLE
告警系统

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#24]
您好，部分告警系统的译文有误，比如“Warning”应该是“告警”而不是“预警”。部分译文缺乏一致性，比如“Threat Type”似乎有“辐射源”、“威胁源”几种译法。另外，由于游戏内RWR没有IFF功能，建议删除“敌”前缀。
请参考以下修改：
将“雷达预警”改为“雷达告警”
将“激光警报”改为“激光告警”
将“威胁探测上限”改为“威胁跟踪上限”
将“敌跟踪”改为“跟踪”
将“敌导弹”改为“发射”
将“锁定状态探测”改为“跟踪状态检测”
将“敌导弹发射探测”改为“发射状态检测”
将“激光测距指示器”改为“激光指示器”
将“告警界面威胁源显示上限”改为“威胁类型显示上限”
将“特征性辐射源”改为“具体威胁类型”
……
中英文词条之间似乎存在较大差异。请问是因为翻译的源语言是俄文吗？还是因为Gaijin没有及时发送更新的文本？我猜测很多错误都是相关机制不完善造成的。

**Comment by YukinonV** [comment]
您好，感谢反馈
Warning作预警用法应该是旧词条遗留，会尽快对措辞存在不一致问题进行排查，Threat type统一为“威胁（来）源”，Warning统一作告警。

敌导弹和敌跟踪是有意贴近国产语音告警系统措辞而拟定的翻译，会根据后续反馈决定是否更改。

RWR描述如Tracked threats和Identified threats是上版本测试服时拟定的，中途词条有变更。谨慎起见我会再次测试一下对应描述。

**Comment by YukinonV** [comment]
RWR描述相关词条我的大致想法是这样的，供讨论：
Scope即座舱内的RWR仪表界面（公告中提到过）
Threat types见于SPO-15和AN/APR-36这种有威胁指示面板的中间型号RWR，即有AAA/AI这类图标的设备，作威胁类型我觉得是比较合适的
Tracked threat仅见于AN/ALR-56M这类最新式RWR，根据拆包内容推测为对威胁源探测数量（跟踪、发射）的探测上限
Threat types on scope是目前比较不确定的一项，文本经过变动，目前推测是RWR可以精确辨别型号的数量（37数值可能是真实数值，也可能只是游戏中存在的特征性雷达波数量，因为SPO L-150和AN/ALR-56M的这个数值是一样的）。基于这一假设，这个词条目前译作“告警界面威胁源显示上限”显然有些不妥。似乎可以改为“告警界面威胁源精确辨识数”（具体措辞有待研究）。

Tracking/Launch detection已经更改为跟踪/发射状态探测，告警/预警不一致的问题目前还在排查。

**Comment by YukinonV** [comment]
有关Threat types on scope，AN/ALR-56M和SPO L-150的文件里都出现了同一组代码：

> "targetsDirectionGroups": {
>     "targetsDirectionGroup": [
>       {
>         "text": "RLD",
>         "group": "Roland"
>       },
>       {
>         "text": "NVL",
>         "group": "Naval"
>       },
>       {
>         "text": "2S6",
>         "group": "2S6"
>       },
>       {
>         "text": "9K3",
>         "group": "9K330"
>       },
>       {
>         "text": "S1",
>         "group": "S1"
>       },
>       {
>         "text": "AAA",
>         "group": "AAA"
>       },
>       {
>         "text": "CRL",
>         "group": "Crotale"
>       },
>       {
>         "text": "SNL",
>         "group": "Santal"
>       },
>       {
>         "text": "NVL",
>         "group": "Naval"
>       },
>       {
>         "text": "M19",
>         "group": "MiG-19"
>       },
>       {
>         "text": "M21",
>         "group": "MiG-21"
>       },
>       {
>         "text": "M23",
>         "group": [
>           "MiG-23",
>           "MiG-23 CW"
>         ]
>       },
>       {
>         "text": "M29",
>         "group": [
>           "MiG-29",
>           "MiG-29 CW"
>         ]
>       },
>       {
>         "text": "F3",
>         "group": [
>           "F-3",
>           "F-3 CW"
>         ]
>       },
>       {
>         "text": "F8",
>         "group": "F-8"
>       },
>       {
>         "text": "F4",
>         "group": [
>           "F-4",
>           "F-4 CW"
>         ]
>       },
>       {
>         "text": "104",
>         "group": [
>           "F-104",
>           "F-104 CW"
>         ]
>       },
>       {
>         "text": "F5",
>         "group": "F-5"
>       },
>       {
>         "text": "F14",
>         "group": [
>           "F-14",
>           "F-14 CW"
>         ]
>       },
>       {
>         "text": "F16",
>         "group": [
>           "F-16",
>           "F-16 CW"
>         ]
>       },
>       {
>         "text": "F18",
>         "group": [
>           "F-18",
>           "F-18 CW"
>         ]
>       },
>       {
>         "text": "TRF",
>         "group": [
>           "Tornado F",
>           "Tornado F CW"
>         ]
>       },
>       {
>         "text": "HRR",
>         "group": "Harrier"
>       },
>       {
>         "text": "TRG",
>         "group": "Tornado Gr1"
>       },
>       {
>         "text": "4050",
>         "group": "Vautour"
>       },
>       {
>         "text": "M3",
>         "group": "Mirage-3"
>       },
>       {
>         "text": "MF1",
>         "group": "Mirage F1"
>       },
>       {
>         "text": "M2K",
>         "group": "Mirage 2000"
>       },
>       {
>         "text": "A32",
>         "group": "A-32"
>       },
>       {
>         "text": "J35",
>         "group": "J-35"
>       },
>       {
>         "text": "J37",
>         "group": "J-37"
>       },
>       {
>         "text": "J7",
>         "group": "J-7"
>       },
>       {
>         "text": "J8",
>         "group": [
>           "J-8",
>           "J-8 CW"
>         ]
>       },
>       {
>         "text": "S125",
>         "group": "S-125"
>       },
>       {
>         "text": "2S6",
>         "group": "2S6"
>       },
>       {
>         "text": "9K3",
>         "group": "9K330"
>       },
>       {
>         "text": "ADS",
>         "group": "ADATS"
>       },
>       {
>         "text": "RLD",
>         "group": "Roland"
>       },
>       {
>         "text": "CRTL",
>         "group": "Crotale"
>       },
>       {
>         "text": "ASD",
>         "group": "ASRAD"
>       },
>       {
>         "text": "AAA",
>         "group": "AAA"
>       },
>       {
>         "text": "NVL",
>         "group": "Naval"
>       },
>       {
>         "text": "MSL",
>         "group": "ARH"
>       }

这组代码规定了告警界面显示的43个提示符，去除掉其中重复的（同型号辐射源跟踪/导弹发射，NVL重复3次，RLD/9K3/2S6/AAA重复2次），大致就是37个。作为对比，Threat types on scope为3的ARI 182228的targetsDirectionGroups代码如下：

>  "targetsDirectionGroups": {
>     "targetsDirectionGroup": [
>       {
>         "text": "E-H",
>         "group": "E-H"
>       },
>       {
>         "text": "I",
>         "group": [
>           "I",
>           "I+TWS",
>           "I+HPRF",
>           "I+MPRF+CW",
>           "I+CW"
>         ]
>       },
>       {
>         "text": "J",
>         "group": [
>           "J",
>           "J+TWS",
>           "J+CW"
>         ]
>       }

可见这个Threat types on scope其实是告警界面能显示的威胁源提示符数目（无论是型号还是波段提示）。因此“告警界面威胁源显示上限”这个提法还是比较贴切的。

**Comment by YukinonV** [comment]
LDR作“激光测距指示器”讲法没有太大问题，这种设备本身就具备测距/目标指示两种功能，故不更改。
“特征性辐射源”提法只在RWR介绍文字中出现，应该不至于引起语义混淆，视后续反馈情况而定。

**Comment by JackerGamer** [comment]
感谢您的详细解答，您的考虑十分周到，我期待着后续的更新。

我想顺便补充几点说明：

> 将“告警界面威胁源显示上限”改为“威胁类型显示上限”

这里只是简化表达，原来的译文也没有错。

> 将“特征性辐射源”改为“具体威胁类型”

这里是因为“特征性”一词比较少见（也有可能是我孤陋寡闻了）。

>跟踪状态/导弹发射探测（仅“发射状态”语义不明确）

跟踪本机、攻击本机可能是语义最明确的？
