### ISSUE TITLE
切换飞控模式->切换操控模式

### ISSUE THREAD

**Issue by Potat0Servers** [YukinonV/WTCNtranslations#25]
<img width="644" alt="image" src="https://github.com/YukinonV/WTCNtranslations/assets/66018299/61909ab8-62f5-4aa8-bd62-f74fb0fab99a">
之前也是我提的修改。改成 操控模式 和上下文统一，更严谨些。

**Comment by YukinonV** [comment]
感谢反馈，已经进行修改，统一为“操控模式”
