### ISSUE TITLE
雷达HUD的空战机动模式

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#26]
这条应该是漏网之鱼，其他模式名称早就改为英文缩写了。
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/74e25cff-0c20-43a6-889d-371406d28f96)

**Comment by Zyszhao** [comment]
似乎是格斗都漏网之鱼了
除了ACM PD，普通格斗和ACM MTI也漏掉了

**Comment by YukinonV** [comment]
感谢您的反馈
已对雷达面板中ACM、ACM PD、ACM MTI、ACM IR等HUD元素进行了统一。

**Comment by Zyszhao** [comment]
请问截获部分有统一吗？刚想起来还有“截获”（按锁定的一瞬间）的词条，也是中文

**Comment by YukinonV** [comment]
> 请问截获部分有统一吗？刚想起来还有“截获”（按锁定的一瞬间）的词条，也是中文

对 ACQ 部分一并进行了统一
