### ISSUE TITLE
某些舰艇关键词翻译缺失造成的混淆

### ISSUE THREAD

**Issue by qzwww1234** [YukinonV/WTCNtranslations#28]
本期通行证中挑战任务中出现的任务要求“炮艇”击杀，英文原文为motor gunboat，但在中文翻译内容时，与例如雷暴级的舰种gunboat均统一翻译为炮艇，易造成混淆影响游戏任务的进行，建议可以将该舰种及任务要求中的描述优化为机动炮艇或摩托炮艇，并同时修正其他带motor前缀的舰艇种类以避免混淆

**Comment by YukinonV** [comment]
您好，感谢您的反馈
Motor gun boat和Gunboat重复为“炮艇”的问题是之前翻译所遗留下来的。我们自己在通行证解锁后也遇到了相关问题，并在第一时间将载具词条与任务条件中的Motor gun boat改成了“机动炮艇”以示区分，但是相关变动显然没能在第一时间实装（俄罗斯法定新年假日为12月31日至1月8日）。
目前舰艇类别中带motor的只有Motor torpedo boat和Motor gun boat两类，前者主要与Motor Torpedo Gun Boat（鱼雷炮艇）与Hydrofoil Torpedo Boat（水翼鱼雷艇）相区分，目前尚不存在命名重复的问题，因此仅对炮艇相关词条进行了修正。
