### ISSUE TITLE
部分载具的绰号使用“”包裹

### ISSUE THREAD

**Issue by Zyszhao** [YukinonV/WTCNtranslations#29]
目前游戏内 F-111A 歼轰-7A（阿提拉之子更新的载具）等载具的全名中的绰号被“”包起来，与其他大部分载具使用空格断开不同

更新：萨姆贝德（以色列超神秘）的绰号也被包裹，且与其他客户端不同短命名仍为超神秘

再次更新：地面载具很多也有这种情况……不过似乎英文词条也有引号

**Comment by YukinonV** [comment]
您好，感谢反馈
目前暂行规则是昵称/代号等非正式名称采用引号，正式名称仅以空格隔开
