### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by Zyszhao** [YukinonV/WTCNtranslations#3]
units:
uk_cruiser_tiger 和 it_destroyer_leone_class_tigre 在目前的汉化文本里都是 _虎_  ；uk_frigate_leopard 和 germ_destroyer_class1924_leopard1932 都是 _豹_ ；请问有没有什么方法可以把这些区分开？

units_modifications:
发动机 engine_model/astazou_14 ; engine_model/adour_mk102 文本有引号，按现状应当删去。

units_weaponry:
cn_fs_70 和 us_2_75_in_wafar_hydra ; 70mm_Hydra_70_user_cannon 等的显示皆为 _火蛇 70_ ，可以对其进行区分吗？

**Comment by YukinonV** [comment]
感谢您的反馈，相关修改会在后续的日志中提及
