### ISSUE TITLE
两个头衔的翻译问题

### ISSUE THREAD

**Issue by Potat0Servers** [YukinonV/WTCNtranslations#34]
原头衔英文：1v1 duelist 和 1v1 master-duelist
![image](https://github.com/YukinonV/WTCNtranslations/assets/66018299/d99f8dc1-fc8b-4074-80ab-bc2c2609ca25)

![image](https://github.com/YukinonV/WTCNtranslations/assets/66018299/f3372c9e-540a-4480-adc4-6efb673aca1a)

现在的翻译：1v1 专家 和 1v1 大师
![image](https://github.com/YukinonV/WTCNtranslations/assets/66018299/b4bcb83c-5696-4177-86be-2a4ab5ab2dd7)

![image](https://github.com/YukinonV/WTCNtranslations/assets/66018299/7ff7d180-60d0-4088-9f25-abb7505d5664)

个人认为应该改成的翻译：1v1 决斗家 和 1v1 决斗大师

**Comment by YukinonV** [comment]
感谢反馈
您的意见已经采纳，相关词条已经进行了修改。

**Comment by Potat0Servers** [comment]
> 感谢反馈 您的意见已经采纳，相关词条已经进行了修改，2v2比赛相关成就的头衔名称也对照进行了修改。

谢谢雪乃酱w
