### ISSUE TITLE
关于竞技场头衔的翻译问题

### ISSUE THREAD

**Issue by SeclusionalAgar** [YukinonV/WTCNtranslations#36]
在英文原文中，gaijin使用了duelist这一词汇，而duelist这个词汇本就包含了1v1的意思，属于是gaijin起名字有问题……专家和大师的翻译主要问题在于专家和大师的级别区分不够明显；当下决斗家、决斗宗师、竞技场英雄的问题在于，决斗宗师和竞技场英雄间的差异不够明显。
经过国内锦标赛圈子的一顿集体讨论，我们认为使用“行家、大师、竞技场英雄”较为合理，能够明显的区分开三个层次。

**Comment by Potat0Servers** [comment]
1

**Comment by SeclusionalAgar** [comment]
> 感谢反馈 现在按照意见修改如下： 1v1/2v2 Duelist - 1v1/2v2 行家 1v1/2v2 Master-duelist - 1v1/2v2 大师 Duelist-hero - 竞技场英雄
感谢作者考虑我的建议，但您可能有轻微的所指偏差。Duelist Hero目前的翻译“决斗英雄”是没问题的，仅需修改1v1/2v2 Duelist与1v1/2v2 Master-duelist。
在竞技场中头衔的分级是1v1/2v2 Duelist -> 1v1/2v2 Master-duelist -> Air Tournament Hero，与之对应的中文：1v1/2v2 行家，1v1/2v2 大师，空战竞技场英雄。

**Comment by JackerGamer** [comment]
某聊天机器人对“决斗”（Duel）的解释：

> 虽然‘决斗’（Duel）传统上特指1v1的个人对抗，但在现代用法中，尤其在游戏和竞技活动中，它可以延伸至描述小规模团队间的直接对抗，如2v2或3v3等形式，这种用法通常会明确指出参与人数。

因此我觉得这样的层次是比较清晰的：

> Duelist - 决斗者
> Master-duelist - 决斗大师
> Duelist-hero - 决斗英雄

其他包含“hero”的现有词条：

> Air Tournaments Hero - 空战竞技场英雄
> Beach Heroes - 喋血滩头
> Combined Tournaments Hero - 联动战斗竞技场英雄
> Hero of the Colosseum - 斗兽场英雄
> Hero of the Olympus - 奥林匹斯英豪
> Racing Tournaments Hero - 竞速赛竞技场英雄
> Tank Tournaments Hero - 陆战竞技场英雄

**Comment by YukinonV** [comment]
>感谢作者考虑我的建议，但您可能有轻微的所指偏差。Duelist Hero目前的翻译“决斗英雄”是没问题的，仅需修改1v1/2v2 Duelist与1v1/2v2 Master-duelist。
>在竞技场中头衔的分级是1v1/2v2 Duelist -> 1v1/2v2 Master-duelist -> Air Tournament Hero，与之对应的中文：1v1/2v2 行家，1v1/2v2 大师，空战竞技场英雄。

参照您的意见将Duelist Hero重新恢复为决斗英雄，其余头衔不变，目前头衔逐级为

1v1/2v2 Duelist - 1v1/2v2 行家
1v1/2v2 Master-duelist - 1v1/2v2 大师
Duelist-hero - 决斗英雄
