### ISSUE TITLE
几辆金车的中系符号可以改吗？

### ISSUE THREAD

**Issue by blyatman996** [YukinonV/WTCNtranslations#37]
上个版本，英文版道尔的中系符号去掉了（毕竟毛子现在无意在苏系加道尔了）
这个版本中文也跟进去掉了道尔的中系符号

现在想问一下：T-26 531、 T-34 215、  IS-2 402、  T-62 545 这几辆车的上个版本英文版中系符号也去掉了
但是这个版本中文版没有跟进

请问是汉化组对此有什么自己的见解吗？还是喜闻乐见的Gaijin本地化负责团队对接负责人不上心的工作流问题（楽）

**Comment by YukinonV** [comment]
感谢反馈
由于这些载具的英文词条没有退回要求更新翻译，所以未能及时更新。
目前经过考虑后，对于中国科技树中的外来装备命名整体规则大致变动如下：
1. 出于某些原因先行加入中系，后续不排除原产国也一并获得的装备（道尔M1、F-5A）暂时加上五星识别标识，视后续实装情况决定是否保留（道尔M1随后移除国籍标）。
2. 与原版装备仅有编号、部队名称和涂装之别的（如545、402等），原先英文原文加注国籍标的情况下一并添加，如果英文存在错漏、或可能存在重名冲突的情况会加注国籍标。目前我们的暂行方案为去除科技树名称和击杀记录中的国籍标，但保留资料卡详细名称中的相关标识。如果实装后玩家认为没法记住那么多特殊载具的单位名，存在信息缺失等问题（如缴获545击杀苏军原版T-62导致阵营辨识出现问题等情况），乃至希望进一步简化击杀记录显示信息等问题，不排除将“换皮”载具的击杀记录名称改成国籍标+装备型号的形式。

现（未实装）
T-62 (“545”号) - 科技树图标名称
␗T-62 (苏军“545”号) - 资料卡详细名称
T-62 (“545”号) - 击杀记录名称

拟（等待后续反馈）
T-62 (“545”号) - 科技树图标名称
␗T-62 (苏军“545”号) - 资料卡详细名称
␗T-62 - 击杀记录名称

**Comment by blyatman996** [comment]
感谢解惑
