### ISSUE TITLE
low clouds 错误翻译为少云，实际上是云层低的意思，麻烦翻译组想个合适的词

### ISSUE THREAD

**Issue by Potat0Servers** [YukinonV/WTCNtranslations#38]
![0fa000f2632bb418515d1dd5263dbc93](https://github.com/YukinonV/WTCNtranslations/assets/66018299/bdc67bdc-87dc-4dd8-9f67-1f2812f6eee8)

**Comment by YukinonV** [comment]
感谢反馈
计划直接用气象学上对高度在2000米以下的“低云”分类进行指代，更正原先的语义歧义
