### ISSUE TITLE
导弹属性翻译

### ISSUE THREAD

**Issue by sreventon** [YukinonV/WTCNtranslations#39]
![屏幕截图 2024-04-09 181214](https://github.com/YukinonV/WTCNtranslations/assets/11544537/7a58d145-85a2-435d-9ea7-d3e3a57db8f8)

这里的“击落”应翻译为“下射”，“下视””下射“是这方面的常用翻译。

**Comment by YukinonV** [comment]
感谢反馈
这一问题在版本更新后已经排查更正，但更改之后的内容没有及时更新进游戏内。
