### ISSUE TITLE
关于战机挂载的翻译问题

### ISSUE THREAD

**Issue by GHOSTLYH** [YukinonV/WTCNtranslations#4]
目前在游戏中左上角数据栏，空对空导弹（AAM）显示的是空对空，空对地导弹（AGM）显示的是空对地，但制导炸弹显示的是制导炸弹，铁炸弹显示的是炸弹，既然后两者显示的都是（形容词）+名词，个人认为导弹应该改空对空导弹（AAM）为空空导弹，空对地导弹（AGM）为空地导弹，不仅是四个字长短一致，方便阅读而且含义清晰，而原文的空对空与地对地无法清晰表明是什么挂载。
![image](https://user-images.githubusercontent.com/60649718/194208427-84c29ec8-5bcb-4a97-8b01-5774aad50899.png)

**Comment by YukinonV** [comment]
感谢您的反馈

**Comment by JackerGamer** [comment]
现阶段或许可以改为“空空弹‘和”空地弹“？另外”高度值“改为”高度“是否更好？

**Comment by GHOSTLYH** [comment]
“空空弹”和“空地弹”确实不失为一个好建议，不知道“激光警”能不能改的不抽象一点，“敌激光”怎么样，顺带一提，ZPZ02也就是QN506主炮的炮弹是不是应该改为DTC10-30（APDS）和DTC04-30（APFSDS）

**Comment by YukinonV** [comment]
> 现阶段或许可以改为“空空弹‘和”空地弹“？以及”高度值“改为”高度“是否更好？ ![image](https://user-images.githubusercontent.com/94670721/234738394-39a8ea47-9a9b-485a-990b-92f3b6a0273e.png) 另外如图所示，两个问题：AUTO没有翻译、油温和引擎的数字为全角。

不错的建议。直升机机炮光电锁定的AUTO词条应该是没有提交本地化部门，因为ui.csv里没有这一条。

> “空空弹”和“空地弹”确实不失为一个好建议，不知道“激光警”能不能改的不抽象一点，“敌激光”怎么样，顺带一提，ZPZ02也就是QN506主炮的炮弹是不是应该改为DTC10-30（APDS）和DTC04-30（APFSDS）

游戏里的LWS是没有IFF功能的，“敌激光”存在歧义，因为游戏里还是有很多整蛊玩家喜欢用激光照队友。
QN506的词条尚未提交本地化部门进行翻译，目前应该还是复制自俄国30炮的文本。

**Comment by JackerGamer** [comment]
> 以及”高度值“改为”高度“是否更好？ 

（我觉得这个可以优先修改）

**Comment by YukinonV** [comment]
> “空空弹”和“空地弹”确实不失为一个好建议，不知道“激光警”能不能改的不抽象一点，“敌激光”怎么样，顺带一提，ZPZ02也就是QN506主炮的炮弹是不是应该改为DTC10-30（APDS）和DTC04-30（APFSDS）

国产30炮只有APDS提供了单独的词条，APFSDS词条直接套用了俄国3UBR11，因此很遗憾只有APDS和HE词条能够体现国产化。

> 提醒一下，我觉得这个可以优先修改

ALT已修改为“高度”，等待实装
