### ISSUE TITLE
联队军衔 Grade/Title

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#40]
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/213d5b68-4262-425a-9d19-88624894c634)
这里多了个“讲”字，另外建议把“军阶”修改为在简体中更常见的“军衔”

**Comment by YukinonV** [comment]
感谢反馈
文本错误已经修正，但联队官阶目前只有军士和指挥官几个等级，此外容易和玩家个人等级相关的真正军衔相混淆，因此不做改动。
