### ISSUE TITLE
强-5L吊舱

### ISSUE THREAD

**Issue by sreventon** [YukinonV/WTCNtranslations#41]
吊舱的名字还是有错误，看起来是修过但是没修完全
![屏幕截图 2024-05-20 213432](https://github.com/YukinonV/WTCNtranslations/assets/11544537/9d5f2c04-a51b-4860-8f91-f3ac5208f631)
![屏幕截图 2024-05-20 213504](https://github.com/YukinonV/WTCNtranslations/assets/11544537/adf4ddf3-80db-4f40-bfab-7310edd4c19b)
![屏幕截图 2024-05-20 213757](https://github.com/YukinonV/WTCNtranslations/assets/11544537/f46c5f07-b13d-4514-946d-c27b68324761)

**Comment by YukinonV** [comment]
感谢反馈
挂载列表中的K/PZS-01 瞄准吊舱名称已经修正
