### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by Zyszhao** [YukinonV/WTCNtranslations#42]
1.意大利 CM52(M45) 中M45炮座和中系CCKW 353/M45统一成斜杠？
2.瑞典Pbv 302/BILL全称错写成301式

**Comment by YukinonV** [comment]
感谢反馈
第一个问题按照炮座/武器站/炮塔的规范现已统一处理为 (M45)；第二项错漏已经修正，等待实装
再次感谢您协助排查付出的努力
