### ISSUE TITLE
关于“您已购买一架”翻译的探讨

### ISSUE THREAD

**Issue by blyatman996** [YukinonV/WTCNtranslations#43]
最近开线打出了一台PGZ04A
查询战斗记录时，发现记录条目为

> 您已购买一架PGZ04A

这实际是有些不确切的，毕竟陆战用“辆”，空战用”架“，海战用”艘“，这样才合适
查阅英文原文，果然：

> You have purchased a PGZ04A.

很明显，最可能的情况是，毛子只做了 You have purchased a 一个条目，因此只能将“a”与“一架”生硬地匹配
但是解决措施也很简单：没有必要逐字逐句翻译，You have purchased a 直接翻译为 “您已购买”即可
毕竟事事物物加“一个”这种冠词本身也是语言欧化的一个特点，其携带的信息本来就是可以略过的

**Comment by YukinonV** [comment]
您好
感谢反馈，词条的确是这样安排的，算是《飞机世界》时期的遗留问题。
已经修正为“您已购买”，等待实装
