### ISSUE TITLE
激活备用载具的提示

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#44]
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/4aa1a9f2-a21b-461b-b766-65a57cce9c5d)

**Comment by YukinonV** [comment]
感谢反馈
原词条在提交翻译时变量未设置清楚，现已更正为 确认要为 {unitName} 激活 {spareName} 吗？
等待实装
