### ISSUE TITLE
空战·历史性能的模式设置

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#45]
![image](https://github.com/YukinonV/WTCNtranslations/assets/94670721/9d1f123c-c9c1-4cb8-ac11-241e03fe754e)
`minMRankForNightBattles`参数在中文本地化未正确替换为具体数值（似乎是10.0？）

**Comment by YukinonV** [comment]
感谢反馈
这里是一处变量套用错误。非常抱歉在审校时没有及时发现这一问题，现已更正为正确的变量{minMRankForSmallTeamsBattles}，等待实装
