### ISSUE TITLE
更准确的服务器名称

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#46]
![image](https://github.com/user-attachments/assets/efdf1379-78f2-4331-a900-e72b79eb4ae3)
![image](https://github.com/user-attachments/assets/938e5f56-e086-43b8-b80c-32e17c724d2e)

首先，我认为此处无需添加“服”或“区”后缀，或者至少统一后缀。其次，虽然“俄服”这个称呼被广泛使用，但毕竟独联体不等于俄罗斯。第三，“North America”严格意义上是自然地理学的北美洲，而非政治地理学的北美地区“Northern America”。尽管Gaijin大概没有这么细节，但咱们准确一点也不是坏事。以下两个方案供您参考，前者注重专业性、后者注重易读性：

> 独立国家联合体（独联体）
> 欧洲联盟（欧盟）
> 北美洲（北美）
> 自动选择（南亚）

> 独联体（俄服）
> 欧盟（欧服）
> 北美（美服）
> 自动选择（亚服）

**Comment by YukinonV** [comment]
感谢反馈
冗长的“独立国家联合体地区”已经缩略为“独联体”
关于“俄区”一词的定夺问题，在处理词条的时候主要考虑到“俄区”在游戏玩家语境中的特殊意义，此外由于众所周知的原因，游戏在俄罗斯的服务已经与国际部分相对独立，且独联体这一概念的存在感已经越来越弱。出于排版美观考虑，“地区”二字仍然是必要的

因此修正如下：

> 独联体（俄服）
> 欧盟地区（欧服）
> 北美地区（美服）
> 自动选择（亚服）

**Comment by JackerGamer** [comment]
> 感谢反馈 冗长的“独立国家联合体地区”已经缩略为“独联体地区” 我的个人意见是没有必要精确到“南亚”这个地步，南亚给人的印象更偏向印度区域，但是说到底服务器在印度还是在新加坡并不影响国内玩家的选择，毕竟大多数国内玩家是使用加速器进行IP切换而不是使用VPN对服务器精确制导。 关于“俄区”一词的定夺问题，在处理词条的时候主要考虑到“俄区”在游戏玩家语境中的特殊意义，此外由于众所周知的原因，游戏在俄罗斯的服务已经与国际部分相对独立，且独联体这一概念的存在感已经越来越弱。出于排版美观考虑，“地区”二字仍然是必要的。
> 
> 因此修正如下：
> 
> > 独联体地区（俄服）
> > 欧盟地区（欧服）
> > 北美地区（美服）
> > 自动选择（亚服）

感谢修正，我认同您的方案
