### ISSUE TITLE
空战·全真模拟的排队匹配选项

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#47]
![image](https://github.com/user-attachments/assets/af87f9a5-1a1b-436b-bfc8-4c8c14946dde)
![image](https://github.com/user-attachments/assets/e6960032-cc38-4db8-ac7b-1e4be00ce9a0)

“重建”似乎是笔误，选项注释也可以稍加改进：

> 玩家创建的房间
> 将玩家创建的房间纳入匹配搜索范围

**Comment by YukinonV** [comment]
感谢反馈
这一遗留问题先前已经更正，但menu.csv词条文件一直没能更新，恐怕要等到新版本才能实装修复了
