### ISSUE TITLE
手游奖励谢尔曼

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#49]
![image](https://github.com/user-attachments/assets/64b0f31b-c8db-4790-a13e-f061d3c476e8)
![image](https://github.com/user-attachments/assets/f5dcb383-c45a-4b33-a399-ee1b71385a51)

一个小问题，手游奖励谢尔曼M4的“天气状况”应改为“获取条件”。另外，建议统一把“War Thunder”替换为“战争雷霆”、“War Thunder Mobile”替换为“战争雷霆手游”，并视情况添加书名号“《》”，减少中英混用的情况。

感谢！

**Comment by YukinonV** [comment]
感谢反馈
目前手游端尚无正式译名（至少谷歌商店仍然是War Thunder Mobile），“天气状况”一词是复用了11年前旧词条的结果，后者目前已经修正。
我们先前已在逐步将游戏中的War Thunder替换成官方译名“战争雷霆”，感谢您的支持

**Comment by JackerGamer** [comment]
官方至少用过四种不同的WT Mobile中文名称，也是够混乱的：
[战争雷霆手游](https://www.bilibili.com/video/BV1Gse4e3EcG)、[战争雷霆手游版](https://play.google.com/store/apps/details?id=com.gaijingames.wtm&hl=zh)、[战争雷霆移动版](https://warthunder.com/zh/news/965)、[战争雷霆移动端](https://warthunder.com/zh/news/1128)。
我觉得与其纠结哪个是“正式”名称，不如先选一个用着。

**Comment by YukinonV** [comment]
![1ccf0f83fccdc9ca8f116a9afc948bbf](https://github.com/user-attachments/assets/6b64aa3b-e89e-4e2f-b353-d6ef697e384e)
词条复用，目前翻译已经回滚到“条件”，等后续开发细化词条（大概率不会）
