### ISSUE TITLE
一个测试服翻译的问题

### ISSUE THREAD

**Issue by Zyszhao** [YukinonV/WTCNtranslations#5]
在测试服实装且提到了修改的翻译里有个问题：
jp_type_90b 没有和其他日系车一样改成“战车”，仍为“坦克”

**Comment by Zyszhao** [comment]
追加，这些问题可能在前版本已经存在：
cn_ztz_99_w_0的两个括号中间缺少空格
il_centurion_shot_kal_d的“绍特 卡尔”错误的出现了空格
b_26c_france_0错误的出现了引号，部分美空载具、日本轰炸机和me-262a-1a_0可能也存在此问题

**Comment by YukinonV** [comment]
已经解决了，感谢您的反馈 : )
