### ISSUE TITLE
贴花解锁条件的“完成次数”

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#50]
有吧友反映“中国人民志愿空军”贴花解锁条件的描述存在歧义。该条件的英文为“missions won:”，当前译文为“完成次数：”，但这一表述缺少宾语，建议修正为“任务完成数：”或“胜利战局数：”。

相关链接: https://tieba.baidu.com/p/9163049396

**Comment by YukinonV** [comment]
感谢反馈
所有missions won任务条件均已更改成“胜利场次”

**Comment by YukinonV** [comment]
![cd5b82580e4497cbe22c8c5ee520d54b](https://github.com/user-attachments/assets/82957e79-98cc-4f13-bd11-4c470cf4a72a)
相关词条目前已获更正
