### ISSUE TITLE
消息界面的“已使用道具”

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#51]
![image](https://github.com/user-attachments/assets/9ac686d6-f145-4414-80fb-b7b5517cddb8)
![image](https://github.com/user-attachments/assets/abc0fc57-e3bc-4464-9e46-1860d589605d)
建议改为“已激活”和“已消耗”，以区分增益方案的状态。

**Comment by YukinonV** [comment]
感谢反馈
相关词条之前曾经有计划更改成激活/消耗，但是后来貌似是有一类道具套用存在冲突（具体是哪一类我忘了，需要重新测试），所以就没有更改。计划在对库存中所有可用道具类别尝试一次之后再做决定。

**Comment by JackerGamer** [comment]
感谢解释，期待后续的测试和改进。

**Comment by YukinonV** [comment]
对应词条已经替换为已激活/已消耗+道具
