### ISSUE TITLE
夜间战斗头衔“黯影战士”

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#52]
![image](https://github.com/user-attachments/assets/8e6c6fd4-0a45-4598-91e8-c3d92c1232b4)
“黯影”似乎不是规范用法，难道是“暗影”的笔误？建议改为“黑夜战士”，和其他两个夜战头衔一样包含“夜”字。

**Comment by YukinonV** [comment]
感谢反馈
“黯影”用法是受全境2的黯牙部队所启发，我的个人意见是在没有语义错误的前提下对于这种纯修饰性的词汇没有必要进行更改，黑夜战士可能不够响亮。

**Comment by JackerGamer** [comment]
我对修饰用法没有异议，但“黯影”与夜间的关联可能不太够，相比之下，使用“暗夜”等明确的词语能让头衔的含义一目了然。
