### ISSUE TITLE
登录界面的“保存登录信息”

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#53]
![image](https://github.com/user-attachments/assets/cda26f1e-f791-4c73-a110-adbafa6970d4) ![image](https://github.com/user-attachments/assets/a13d2aba-c90b-4f1b-a42f-233c0970eb7c)
建议改为“保存账号”或“保存登录名”

**Comment by YukinonV** [comment]
感谢反馈
这个的字面意思是“保存登录邮箱”，但我不确定客户端同界面是否可以通过输入用户名登录，还是只有邮箱选项，需要进行确认。
如果是前者，那么语义更广泛的“登录信息”显然更加适用（就这层意义来说登录信息/账号/登录名并没有本质区别），如果是后者，将会更正为“保存登录邮箱”。

**Comment by JackerGamer** [comment]
输入框的标题为“账号（电子邮件地址）”，我也试过，并不能通过用户名登录。而且”登录信息“会产生歧义，因为它可以指代整个登录过程中的多种信息，如密码、二步验证等。

**Comment by YukinonV** [comment]
输入框上的原文是Login (Email)，致使login作为其他短句的组成语料被翻译成了“登录信息”
现更改为：
Login (email) → 登录邮箱
Save login → 登录邮箱

对于其他途径如steam登录或网页端Gaijin pass登录不知道会有什么影响，需要后续观察
