### ISSUE TITLE
头衔翻译错误问题

### ISSUE THREAD

**Issue by MeltTrigger** [YukinonV/WTCNtranslations#57]
【Air Superiority Contender】 应该直译成 【苍空卫士参赛者】，而不是【骑空裁决者】

![%1F5$PJXCN`38XTKUEN6SYE](https://github.com/user-attachments/assets/dedb0f09-fc71-4d92-816f-6f30e95cc525)
![9J8UHZ NU~6C ~%A8JQ_Q80](https://github.com/user-attachments/assets/3b561b48-7919-4f5e-9a62-eb3884997376)

**Comment by YukinonV** [comment]
感谢反馈
该头衔在当初翻译时目的是想突出其特殊属性所以给了一个比较文艺化的翻译，当然最终尊重头衔拥有者的意见。Air Superiority Contender已修改为“苍空卫士参赛者”。

**Comment by MeltTrigger** [comment]
如果可以，我还想建议在赛事名称后面加上【锦标赛】三个字，例如【Air Superiority Contender】可以翻译成【“苍空卫士”锦标赛参赛者】，【Air Superiority 2024 Champion】翻译成【2024"苍空卫士"锦标赛冠军】

**Comment by YukinonV** [comment]
个人意见：“参赛者”已经凸显了成就的赛事属性，可能不需要以锦标赛加以强调
Air Superiority 2024 Champion已更改为【2024“苍空卫士”锦标赛冠军】，等待实装
之后类似年份+赛事的头衔格式也将照此办理，如果赛事名称比较长出现适配问题的话则留待之后进一步决定

**Comment by MeltTrigger** [comment]
个人还是建议为在赛事名称后面加上【锦标赛】三个字，一方面可以凸显头衔的价值，另一方面可以一定程度上的激发玩家参加TSS的兴趣，而且还能与修改【Air Superiority 2024 Champion】的头衔名称保持一致，所以我还是建议【Air Superiority Contender】修改成【“苍空卫士”锦标赛参赛者】
