### ISSUE TITLE
“阿尔汉格尔斯克”号战列舰和项目负责人名称

### ISSUE THREAD

**Issue by JackerGamer** [YukinonV/WTCNtranslations#58]
![image](https://github.com/user-attachments/assets/908c5f5b-0cda-47ce-96f6-c4b69735e6af)

> 怎么会是阿尔格汉斯克呢？Архангельск，怎么读也不可能读出来阿尔格汉斯克啊，复仇级租借给红海军的，叫“阿尔汉格尔斯克”才对啊，俄罗斯的一个港口，西北边的

顺便问一下，README.md 里的“雪下之雪乃”是不是笔误？而且单独写个二小姐名称也没啥辨识度，建议标注更具体的信息（平台、ID 等）。

**Comment by YukinonV** [comment]
感谢反馈
这个问题在版本更新后的第一时间就发现并在项目上进行了更正，只是没有更新进游戏。大概要等到开发把现版本文本全部补齐后才会随着后续更新修复。
Readme中的部分已经更正，至于标注具体信息的话，似乎没有太大的必要。作为项目维护者，大家只需要通过项目本身认识我们就够了不是吗？
