### ISSUE TITLE
Ver.2.20 2022.10.15 (未实装) 一个矛盾

### ISSUE THREAD

**Issue by Zyszhao** [YukinonV/WTCNtranslations#6]
cn_ztz_99_w_0 | ZTZ1999 式主战坦克 (III 类定型状态) (WZ123B)
和中系载具编号移除年份的改动是不是自相矛盾？或者说，中系载具编号移除年份的意思具体是什么？

**Comment by YukinonV** [comment]
编号移除年份的意思是指将 YYY XXXX 的格式改为 YYY XX 的格式，例如 ZTQ1962 → ZTQ62。
因为翻译更新有覆盖性，所以放在后面的更新内容会将前面的内容覆盖。：）
