### ISSUE TITLE
海战模块详细内构描述的翻译问题

### ISSUE THREAD

**Issue by Zyszhao** [YukinonV/WTCNtranslations#8]
1：跟踪雷达天线、射击指挥仪和测距仪的翻译没有实装，是有意为之？
2：弹药模块的第三段“另一大敌”后的冒号前面似乎错误的出现了空格？
3：发动机、传动机构和舵机的最后一句我认为应该统一成“可以通过该图标查看XX受损情况”或其他，现在三个的翻译不同

**Comment by YukinonV** [comment]
1. 俄罗斯没有提供文本。
2. 其他部分的内容，感谢您的反馈。

**Comment by YukinonV** [comment]
最新版本客户端中已修复了相应问题，感谢反馈
