### ISSUE TITLE
关于翻译中的机关枪/炮

### ISSUE THREAD

**Issue by Zyszhao** [YukinonV/WTCNtranslations#9]
意大利VCC-80的Bushmaster被翻译成了xxx“机关炮”，词典说明机关枪为机枪旧称，可否由此将所有的“机关枪/机关炮”替换为“机枪/机炮”？

**Comment by YukinonV** [comment]
感谢您的反馈，这一问题将于下一版本更新中修复，我们将使用同一的用词
